sudo: false
language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'

install: "pip install tox"

script:
  - export PYENV=$(python -c 'import sys; print("py%d%d" % (sys.version_info[:2]))')
  - tox --recreate -e "$PYENV"

after_success:
  - if [[ "$PYENV" == "py36" ]]; then
      tox --recreate -e coveralls;
      tox --recreate -e flake8;
    fi
