sudo: false
language: python
python:
    - '3.5'

install: "pip install tox"

env:
  matrix:
    - TESTENV=coveralls
    - TESTENV=py27
    - TESTENV=py33
    - TESTENV=py34
    - TESTENV=py35
    - TESTENV=flake8

script: tox --recreate -e $TESTENV
